apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MrSiddu73/gitops-argocd-kubernetes
    targetRevision: main
    path: apps/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
